# Generated by Django 5.2.7 on 2025-11-04 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_auth', '0002_client_is_staff_client_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitants', to='pf_auth.address'),
        ),
    ]
