# Generated by Django 5.2.7 on 2025-10-28 19:46

import django.core.validators
import django.db.models.deletion
import pf_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('order_serial', models.CharField(max_length=20, unique=True, verbose_name='Numéro de commande')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prix du produit')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='images/', verbose_name='Image')),
                ('position', models.PositiveIntegerField(verbose_name='Position')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pf_main.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pf_main.product')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pf_main.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pf_main.product')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('format', models.CharField(choices=[('pourcentage', 'Pourcentage'), ('monetaire', 'Monétaire')], default='pourcentage', max_length=20, verbose_name='Format')),
                ('value', models.PositiveIntegerField(help_text='Doit être ≤ 100 si format = pourcentage', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur')),
                ('date_debut', models.DateTimeField(default=pf_main.models.default_date_debut, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(default=pf_main.models.default_date_fin, verbose_name='Date de fin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='pf_main.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'constraints': [models.CheckConstraint(condition=models.Q(('format', 'monetaire'), models.Q(('format', 'pourcentage'), ('value__lte', 100)), _connector='OR'), name='promotion_value_constraint'), models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='promotion_date_constraint')],
            },
        ),
    ]
