# Generated by Django 5.2.7 on 2025-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_main', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Position'),
        ),
    ]
