# Generated by Django 5.2.7 on 2025-11-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_main', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Est active'),
        ),
    ]
