# Generated by Django 5.2.7 on 2025-11-19 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pf_main', '0004_alter_image_position'),
        ('pf_main', '0004_promotion_is_active'),
    ]

    operations = [
    ]
