# Generated by Django 5.2.7 on 2025-11-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_main', '0005_merge_20251118_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='product',
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(related_name='promotions', to='pf_main.product', verbose_name='Produit'),
        ),
    ]
