# Generated by Django 5.2.7 on 2025-12-12 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_main', '0007_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='pf_main.category', verbose_name='Catégorie'),
        ),
    ]
