# Generated by Django 5.2.7 on 2025-12-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf_main', '0007_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
    ]
