# Generated by Django 5.2.7 on 2025-12-14 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pf_main', '0008_order_is_paid'),
        ('pf_main', '0008_remove_promotion_is_active_alter_product_category'),
    ]

    operations = [
    ]
